import { type Browser, chromium, expect, type Page, test } from "@playwright/test";

/**
 * Inline image round-trip via Tauri CDP — Tier 🟡 #5 + post-0.2.4 Tier 🔴 #1
 * coverage. The companion of `pty-flows.spec.ts`; CDP attach,
 * skip-when-unreachable, and per-test terminal lifecycle all follow the
 * exact same shape.
 *
 * What this suite proves end-to-end (when the prerequisite is satisfied):
 *
 * 1. The `term_image_data` IPC is wired and returns `null` for an unknown
 *    image id. Smoke-level only; never depends on PTY behaviour.
 * 2. A real PNG piped through `aether-imgcat.ps1` → real PTY → ConPTY →
 *    engine `ChunkAssembler` → `GridSnapshot.images` → `term_image_data`
 *    round-trip surfaces a paint-ready PNG payload to the frontend.
 *    Asserts the PNG signature on the way back.
 *
 * Run prerequisite (same as `pty-flows.spec.ts`):
 *
 *   pnpm tauri:dev   # opens a webview with --remote-debugging-port=9222
 *
 * If port 9222 is not reachable every test in the suite is `test.skip`-ed,
 * matching the no-op behaviour of `pty-flows.spec.ts`. The skip reason is
 * surfaced in the report so a missing Tauri build never turns into a red
 * bar in CI / local dev.
 *
 * Historical note (2026-04-30 → 2026-05-01):
 *
 *   The original test 2 fed a Kitty APC escape (`\x1b_G…\x1b\\`) directly
 *   through `[Console]::Out.Write` and asserted the round-trip. ConPTY on
 *   Win11 25H2 silently strips APC sequences (verified via
 *   `scripts/diag-image-escape.mjs`), so that path was unreachable on the
 *   dogfood machine and the test was `test.fixme`'d.
 *
 *   `docs/ROADMAP_POST_0_2_4.md` Tier 🔴 #1 + Spike 2 introduced a chunked
 *   OSC 1338 protocol that stays under ConPTY's measured ~512-byte cap.
 *   Sprint 1 (a627cb7) shipped the engine assembler, Sprint 2 (112bd23)
 *   shipped `scripts/aether-imgcat.{ps1,sh}` emitters + PNG fixtures.
 *   Test 2 below now drives the chunked-OSC path through the PowerShell
 *   emitter — the fixme is gone, the assertion is identical, only the
 *   vehicle changed.
 */

import { resolve as resolvePath } from "node:path";

const CDP_URL = "http://localhost:9222";
const VITE_HOST = "localhost:1420";
/** Per-test timeout for "wait for snapshot to converge". Generous because
 *  spawning a PowerShell child + reading the PNG + emitting OSC 1338 frames
 *  can take ~1.5 s on Windows under load. */
const SNAPSHOT_TIMEOUT_MS = 8_000;

/** Repo-relative paths to the PNG fixtures the chunked-OSC emitter pipes
 *  through the PTY. `inline-image-1x1.png` is a 68-byte single-chunk PNG;
 *  `inline-image-32x32.png` is ~2.6 KB and crosses the chunk boundary
 *  (~8 DATA frames at the ConPTY cap). Generated by
 *  `scripts/build-image-fixtures.mjs`. */
const FIXTURE_TINY = "e2e/fixtures/inline-image-1x1.png";
const EMITTER_PS1 = "scripts/aether-imgcat.ps1";

/** Project root resolved from the spec file location. Both the emitter
 *  script and the fixture are repo-relative so the test runs identically
 *  regardless of where Playwright was invoked from. */
const REPO_ROOT = resolvePath(__dirname, "..");

interface ImageRef {
  id: number;
  cellRow: number;
  cellCol: number;
  widthPx: number;
  heightPx: number;
  cellW?: number;
  cellH?: number;
}

interface GridSnapshot {
  cols: number;
  rows: number;
  cells: unknown[][];
  cursor: { row: number; col: number };
  images?: ImageRef[];
}

interface ImageDataResponse {
  format: "png" | "rgba8";
  dataBase64: string;
  widthPx: number;
  heightPx: number;
}

let browser: Browser | null = null;
let page: Page | null = null;
let cdpAvailable = false;
let cdpFailureReason = "";

test.describe("Inline image round-trip via Tauri CDP", () => {
  test.beforeAll(async () => {
    try {
      browser = await chromium.connectOverCDP(CDP_URL);
      const ctx = browser.contexts()[0];
      const candidate = ctx?.pages().find((p) => p.url().includes(VITE_HOST));
      if (!candidate) {
        cdpFailureReason = `no Tauri page found at ${VITE_HOST}`;
        await browser.close().catch(() => {});
        browser = null;
        return;
      }
      const hasInternals = await candidate.evaluate(() => {
        const w = window as unknown as { __TAURI_INTERNALS__?: { invoke?: unknown } };
        return typeof w.__TAURI_INTERNALS__?.invoke === "function";
      });
      if (!hasInternals) {
        cdpFailureReason = "page found but __TAURI_INTERNALS__.invoke missing";
        await browser.close().catch(() => {});
        browser = null;
        return;
      }
      page = candidate;
      cdpAvailable = true;
    } catch (err) {
      cdpFailureReason = err instanceof Error ? err.message : String(err);
    }
  });

  test.afterAll(async () => {
    if (browser) {
      // Disconnect, don't tear down — the user owns the Tauri window. We
      // are merely attaching as a tool. Mirrors `pty-flows.spec.ts`.
      await browser.close().catch(() => {});
    }
  });

  test.beforeEach(() => {
    test.skip(!cdpAvailable, `Tauri CDP not reachable: ${cdpFailureReason || "unknown"}`);
  });

  // ---- helpers ------------------------------------------------------------

  const call = async <T>(cmd: string, args?: Record<string, unknown>): Promise<T> => {
    if (!page) throw new Error("page not bound");
    return page.evaluate(
      async ({ cmd, args }) => {
        const w = window as unknown as {
          __TAURI_INTERNALS__: {
            invoke: (cmd: string, args?: Record<string, unknown>) => Promise<unknown>;
          };
        };
        return w.__TAURI_INTERNALS__.invoke(cmd, args);
      },
      { cmd, args },
    ) as Promise<T>;
  };

  const spawnTerminal = async (): Promise<string> => {
    return call<string>("spawn_terminal", {
      shell: "powershell",
      cols: 120,
      rows: 30,
      cwd: "C:\\Users\\owner\\Aether_Terminal",
    });
  };

  const closeTerminal = async (id: string) => {
    try {
      await call<void>("close_terminal", { id });
    } catch {
      /* best-effort cleanup */
    }
  };

  const snapshotGrid = async (id: string): Promise<GridSnapshot | null> =>
    call<GridSnapshot | null>("term_snapshot", { id });

  /** Poll a predicate against fresh snapshots until it succeeds or the
   *  timeout elapses. Mirrors the helper in `pty-flows.spec.ts` but
   *  specialised on `images` so the failure message is actionable. */
  const waitForImages = async (
    id: string,
    timeoutMs: number = SNAPSHOT_TIMEOUT_MS,
  ): Promise<GridSnapshot> => {
    const deadline = Date.now() + timeoutMs;
    let last: GridSnapshot | null = null;
    while (Date.now() < deadline) {
      last = await snapshotGrid(id);
      if (last && Array.isArray(last.images) && last.images.length > 0) return last;
      await new Promise((r) => setTimeout(r, 100));
    }
    const seenImages = last?.images?.length ?? "<absent>";
    throw new Error(
      `waitForImages timed out after ${timeoutMs} ms — ` +
        `last snapshot images=${seenImages} rows=${last?.rows ?? "<null>"}. ` +
        `Most likely cause: ConPTY dropped the Kitty APC escape before it reached the engine.`,
    );
  };

  /**
   * Build a one-liner the spawned PowerShell terminal can execute to drive
   * `aether-imgcat.ps1` against a fixture. `-NoProfile` keeps the prompt
   * deterministic; `-ExecutionPolicy Bypass` is required because the .ps1
   * is unsigned. Path arguments are wrapped in double quotes so spaces in
   * the repo path (rare but possible on Windows) survive PowerShell's
   * argument parsing.
   */
  const chunkedOscCommand = (fixture: string): string => {
    const fixturePath = resolvePath(REPO_ROOT, fixture);
    const emitterPath = resolvePath(REPO_ROOT, EMITTER_PS1);
    return `powershell -NoProfile -ExecutionPolicy Bypass -File "${emitterPath}" "${fixturePath}"\r`;
  };

  // ---- tests --------------------------------------------------------------

  test("term_image_data returns null for an unknown image id", async () => {
    const tid = await spawnTerminal();
    try {
      // No escape was sent, so any imageId is unknown. The IPC must
      // resolve cleanly to `null` rather than throw — the frontend cache
      // (`useTerminalImages`) treats `null` as "drop silently".
      const data = await call<ImageDataResponse | null>("term_image_data", {
        id: tid,
        imageId: 999_999,
      });
      expect(data).toBeNull();
    } finally {
      await closeTerminal(tid);
    }
  });

  test("PNG piped via aether-imgcat surfaces an ImageRef and round-trips bytes back", async () => {
    const tid = await spawnTerminal();
    try {
      // Let the prompt settle so the emitter's output lands cleanly
      // inside the visible grid rather than racing the shell's prompt.
      await new Promise((r) => setTimeout(r, 800));

      await call<void>("write_terminal", {
        id: tid,
        data: chunkedOscCommand(FIXTURE_TINY),
      });

      const snap = await waitForImages(tid);
      expect(snap.images).toBeDefined();
      expect(snap.images!.length).toBeGreaterThan(0);

      const ref = snap.images![0]!;
      // Engine ImageId is u64 starting at 0 — accept any non-negative integer.
      expect(Number.isInteger(ref.id)).toBe(true);
      expect(ref.id).toBeGreaterThanOrEqual(0);
      expect(ref.widthPx).toBeGreaterThan(0);
      expect(ref.heightPx).toBeGreaterThan(0);
      // Anchor must be inside the visible grid — `collect_visible_images`
      // drops anything outside (rows..) before the snapshot is built.
      expect(ref.cellRow).toBeGreaterThanOrEqual(0);
      expect(ref.cellRow).toBeLessThan(snap.rows);

      const data = await call<ImageDataResponse | null>("term_image_data", {
        id: tid,
        imageId: ref.id,
      });
      expect(data).not.toBeNull();
      expect(data!.format).toBe("png");
      expect(data!.dataBase64.length).toBeGreaterThan(0);
      expect(data!.widthPx).toBeGreaterThan(0);
      expect(data!.heightPx).toBeGreaterThan(0);

      // Round-trip integrity: the bytes coming back must still be a PNG.
      // We don't byte-compare against the fixture because the engine
      // re-emits whatever the decoder normalised — for PNG passthrough
      // that's the same bytes, but checking the `\x89PNG` signature is
      // a stable contract that survives any future re-encode.
      const decoded = Buffer.from(data!.dataBase64, "base64");
      expect(decoded.subarray(0, 4)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47]));
    } finally {
      await closeTerminal(tid);
    }
  });
});
