import { lazy } from "react";

export const KanbanBoard = lazy(() => import("../kanban/KanbanBoard").then((module) => ({ default: module.KanbanBoard })));
export const AgentInspector = lazy(() => import("../agent-inspector/AgentInspector").then((module) => ({ default: module.AgentInspector })));
export const WorkstationPulse = lazy(() => import("../context/WorkstationPulse").then((module) => ({ default: module.WorkstationPulse })));
export const SCMPanel = lazy(() => import("../scm/SCMPanel").then((module) => ({ default: module.SCMPanel })));
export const RightRailCommandMode = lazy(() => import("../right-rail/RightRailCommandMode").then((module) => ({ default: module.RightRailCommandMode })));
export const RightRailObserveMode = lazy(() => import("../right-rail/RightRailObserveMode").then((module) => ({ default: module.RightRailObserveMode })));
export const RightRailReviewMode = lazy(() => import("../right-rail/RightRailReviewMode").then((module) => ({ default: module.RightRailReviewMode })));
export const QuickOpen = lazy(() => import("../quick-open/QuickOpen").then((module) => ({ default: module.QuickOpen })));
export const EditorPanel = lazy(() => import("../editor/EditorPanel").then((module) => ({ default: module.EditorPanel })));
export const CommandPalette = lazy(() => import("../command-palette/CommandPalette").then((module) => ({ default: module.CommandPalette })));
export const PaneSwitcherDialog = lazy(() => import("../terminal/pane-switcher").then((module) => ({ default: module.PaneSwitcherDialog })));
export const Settings = lazy(() => import("../settings/Settings").then((module) => ({ default: module.Settings })));
export const WatchdogDialog = lazy(() => import("../watchdog/WatchdogDialog").then((module) => ({ default: module.WatchdogDialog })));
export const WelcomeScreen = lazy(() => import("../welcome/WelcomeScreen").then((module) => ({ default: module.WelcomeScreen })));
export const SearchPanel = lazy(() => import("../search/SearchPanel").then((module) => ({ default: module.SearchPanel })));
export const AboutDialog = lazy(() => import("../about/AboutDialog").then((module) => ({ default: module.AboutDialog })));
export const HelpDialog = lazy(() => import("../help/HelpDialog").then((module) => ({ default: module.HelpDialog })));
export const PRInspector = lazy(() => import("../pr-inspector/PRInspector").then((module) => ({ default: module.PRInspector })));
export const MergeQueuePanel = lazy(() => import("../merge-queue/MergeQueuePanel").then((module) => ({ default: module.MergeQueuePanel })));
export const WebInspector = lazy(() => import("../web-inspector/WebInspector").then((module) => ({ default: module.WebInspector })));
export const FleetHud = lazy(() => import("../fleet-hud/FleetHud").then((module) => ({ default: module.FleetHud })));
export const OnboardingOverlay = lazy(() => import("../../shared/ui/OnboardingOverlay").then((module) => ({ default: module.OnboardingOverlay })));
