import { useShallow } from "zustand/react/shallow";
import { useAppStore } from "../../shared/store/appStore";

export function useAppShellStore() {
  return useAppStore(
    useShallow((state) => ({
      themeId: state.themeId,
      moodPresetId: state.moodPresetId,
      rootProjectPath: state.rootProjectPath,
      setRootProjectPath: state.setRootProjectPath,
      sidebarCollapsed: state.sidebarCollapsed,
      setSidebarCollapsed: state.setSidebarCollapsed,
      sidebarWidth: state.sidebarWidth,
      setSidebarWidth: state.setSidebarWidth,
      rightPanelWidth: state.rightPanelWidth,
      setRightPanelWidth: state.setRightPanelWidth,
      rightRailCollapsed: state.rightRailCollapsed,
      setRightRailCollapsed: state.setRightRailCollapsed,
      productMode: state.productMode,
      setProductMode: state.setProductMode,
      rightRailMode: state.rightRailMode,
      setRightRailMode: state.setRightRailMode,
      rightRailFocusWidget: state.rightRailFocusWidget,
      setRightRailFocusWidget: state.setRightRailFocusWidget,
      hydrateWorkspaceNavigation: state.hydrateWorkspaceNavigation,
      zenMode: state.zenMode,
      setZenMode: state.setZenMode,
      paletteVisible: state.paletteVisible,
      setPaletteVisible: state.setPaletteVisible,
      settingsVisible: state.settingsVisible,
      setSettingsVisible: state.setSettingsVisible,
      watchdogVisible: state.watchdogVisible,
      setWatchdogVisible: state.setWatchdogVisible,
      searchVisible: state.searchVisible,
      setSearchVisible: state.setSearchVisible,
      aboutVisible: state.aboutVisible,
      setAboutVisible: state.setAboutVisible,
      helpVisible: state.helpVisible,
      setHelpVisible: state.setHelpVisible,
      webInspectorVisible: state.webInspectorVisible,
      setWebInspectorVisible: state.setWebInspectorVisible,
      prInspectorVisible: state.prInspectorVisible,
      setPrInspectorVisible: state.setPrInspectorVisible,
      mergeQueueVisible: state.mergeQueueVisible,
      setMergeQueueVisible: state.setMergeQueueVisible,
      openFiles: state.openFiles,
      activeFile: state.activeFile,
      openFile: state.openFile,
      closeFile: state.closeFile,
      clearFiles: state.clearFiles,
      setActiveFile: state.setActiveFile,
      kanbanTasks: state.kanbanTasks,
      moveKanbanTask: state.moveKanbanTask,
      contextWarnPct: state.contextWarnPct,
      resolveWorkspaceProfile: state.resolveWorkspaceProfile,
      setWorkspaceThreadRunState: state.setWorkspaceThreadRunState,
    })),
  );
}
